#!/usr/bin/env python3
"""
Hook: PreToolUse on Write|Edit — Remind to load `instruction_quality` before authoring harness files.

What it does:
- Gates on the tool's file_path: only .claude/ harness surfaces (see PATH RULES).
- DENIES the edit (permissionDecision) until `instruction_quality` appears in the
  session's `skills_loaded` state, written by skill_load_marker.py (PostToolUse on
  Skill). Escalated from advisory: the advisory channel was observed being ignored.
- Once loaded: emits the hookSpecificOutput.additionalContext gates-summary
  advisory. Per the verified channel matrix, additionalContext is the ONLY
  model-visible advisory channel on PreToolUse.
- Dedupes the advisory per session so a multi-edit harness session pays it once.

PATH RULES (in .claude/ only):
- IN:  **/*.md (CLAUDE.md, skills, commands, rules), hooks/*.py, settings*.json
- OUT: auto-memory/** — governed by consolidate-memory / memory_audit, not this
       skill (see instruction_quality "Composition with other tools").
- OUT: scratch/**, tests/**, __pycache__/**, plans/**, .cache/** — not loaded guidance.
- IN (carve-out): pending_harness_edits.md — queued CLAUDE.md/MEMORY.md
  content awaiting /apply_harness_edits; it IS loaded guidance in transit, and
  authoring errors there land verbatim in the injected files.
- Path scope uses `_claude_scope.harness_tail`, which rebases a worktree root before classifying the checkout's own `.claude/`.

Boundaries:
- The deny path is deterministic (harness file AND skill not loaded). Unexpected
  errors exit 0 open — a hook bug must not brick every edit; the marker writer's
  failure direction (keep denying) covers the enforcement side.
- Re-fires the advisory after a compaction, which drops the first one from context.

Wired in: settings.json hooks.PreToolUse with matcher "Write|Edit".
"""

import json
import sys

from _claude_scope import harness_tail
from _hook_state import fire_once_since_compaction, read_json_salvage, state_path

# Key in the per-session routing state file that the other routing hooks share.
STATE_KEY = "harness_edit_reminder"

INCLUDED_MD_ANY_DEPTH = ".md"
INCLUDED_EXACT_DIRS = ("hooks",)          # .claude/hooks/*.py
# plans/: execution docs owned by plan_file_format, not doctrine. .cache/: mirrors (baseline-repo);
# a checkout hosted there is rebased first, so its own .claude/ tail stays gated.
EXCLUDED_DIRS = ("auto-memory", "scratch", "tests", "__pycache__", "plans", ".cache")


def is_harness_file(file_path: str) -> bool:
    """
    True if file_path is a .claude/ surface governed by `instruction_quality`.
    Path separators are normalized — Edit/Write may deliver either on Windows.
    """
    tail = harness_tail(file_path)
    if tail is None:
        return False
    parts = tail.split("/")

    # Queued injected-file content is harness guidance in transit, so the gate
    # covers it even though it is not under a governed subdirectory.
    if tail == "pending_harness_edits.md":
        return True

    # The worklog mirror is generated by /worklog; its quality is owned by that command.
    if tail == "worklog-titles.md":
        return False

    if any(seg in EXCLUDED_DIRS for seg in parts[:-1]):
        return False

    name = parts[-1]
    if name.endswith(INCLUDED_MD_ANY_DEPTH):
        return True
    if name.startswith("settings") and name.endswith(".json"):
        return True
    if name.endswith(".py") and len(parts) > 1 and parts[-2] in INCLUDED_EXACT_DIRS:
        return True
    return False


def build_reminder(file_path: str) -> str:
    name = harness_tail(file_path) or file_path
    return (
        f"Harness edit `.claude/{name}`: apply `instruction_quality`. Most-missed gates: "
        "§3 SSOT (link, don't restate), §4 verify every cited path resolves, "
        "§6 cut non-decision rationale, §7 skill triggers, §13-16 for hooks."
    )


def process(input_data):
    """Dispatcher entry: `{"deny": reason}`, `{"context": reminder}`, or None.

    `pre_edit_dispatch.py` calls this; `main()` keeps the standalone channel.
    """
    if input_data.get("tool_name") not in ("Write", "Edit"):
        return None

    session_id = input_data.get("session_id") or ""
    file_path = (input_data.get("tool_input") or {}).get("file_path") or ""
    if not is_harness_file(file_path):
        return None

    state = read_json_salvage(state_path(session_id))

    skills_loaded = state.get("skills_loaded")
    if not (isinstance(skills_loaded, list) and "instruction_quality" in skills_loaded):
        name = harness_tail(file_path) or file_path
        return {"deny": (
            f"Harness edit to `.claude/{name}` DENIED: invoke Skill(skill=\"instruction_quality\"), "
            "then retry this edit. Only a real Skill call clears the gate, not a compaction summary."
        )}
    # Once per session, and again after a compaction dropped it from context.
    if not fire_once_since_compaction(session_id, STATE_KEY):
        return None

    return {"context": build_reminder(file_path)}


def main() -> None:
    try:
        input_data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)

    result = process(input_data) or {}
    if result.get("deny"):
        sys.stdout.write(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": result["deny"],
            }
        }))
    elif result.get("context"):
        sys.stdout.write(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "additionalContext": result["context"],
            }
        }))
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        # Advisory hook: never block a harness edit because the reminder broke.
        sys.exit(0)
